<?php

namespace App\Models;

use App\Mail\PasswordReset;
use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Mail;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class User extends Authenticatable  implements HasMedia
{
    use Notifiable;
    use HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'profession',
        'date_of_birth',
        'location_of_birth',
        'street',
        'city',
        'phone',
        'education',
        'email_token',
        'training_date_from',
        'training_date_to',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function tags()
    {
        return $this->hasMany(Tag::class);
    }

    public function checks()
    {
        return $this->hasMany(Check::class);
    }

    public function partners()
    {
        return $this->hasMany(Partner::class);
    }

    public function phases()
    {
        return $this->hasMany(Phase::class);
    }

    public function verified()
    {
        $this->verified = 1;
        $this->email_token = null;
        $this->save();
    }

    public function getDateOfBirthAttribute($value)
    {
        return $this->formatDate($value);
    }

    public function getTrainingDateFromAttribute($value)
    {
        return $this->formatDate($value);
    }

    public function getTrainingDateToAttribute($value)
    {
        return $this->formatDate($value);
    }

    public function sendPasswordResetNotification($token)
    {
        Mail::to($this->email)->send(new PasswordReset($this, $token));
    }

    private function formatDate($value)
    {
        if (is_null($value)) {
            return null;
        }
        return Carbon::parse($value)->format('d.m.Y');
    }

    public function isAdmin()
    {
        return (bool)$this->is_admin;
    }

    public function delete()
    {
        foreach ($this->checks()->cursor() as $_check) {
            $_check->delete();
        }

        foreach ($this->tags()->cursor() as $_tags) {
            $_tags->delete();
        }

        foreach ($this->partners()->cursor() as $_partner) {
            $_partner->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
